version: '3'

services:
  postgres-compose:
    image: postgres:latest
    container_name: postgres-finance-simulator
    environment:
      POSTGRES_USER: finance-simulator
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance-simulator
    ports:
      - "5432:5432"